# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'useSwiftLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for useSwiftLibrary
  pod 'lottie-ios'

  target 'useSwiftLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'useSwiftLibraryUITests' do
    # Pods for testing
  end

end
